const years = [
  ["🐖", "2019", "Porco", "Foi o ano em que tudo começou.", "Foi aqui que a gente se conheceu por causa do Blox Strike. Até hoje acho engraçado pensar que uma mensagem no seu privado virou tudo isso."],
  ["🐀", "2020", "Rato", "O clã e aquela época.", "Eu e o Italo ficávamos tentando fazer o clã virar alguma coisa. Até gastei R$200 no Blox Strike com isso kkkkk. Eu estava muito feliz naquela época."],
  ["🐂", "2021", "Boi", "Roblox todo dia.", "Depois vieram o Crys e a Luisa, a Pamonha. A gente jogava Roblox praticamente todo dia, Adopt Me e Marretão. Eu nem gostava de Roblox e você me fez jogar kkkkk."],
  ["🐅", "2022", "Tigre", "As conversas e as lembranças.", "Eu lembro das nossas conversas sobre a escola, sobre sua mãe fazer bolo de fruta e de vários assuntos aleatórios que a gente ficava falando. Eu gostava muito dessas conversas."],
  ["🐇", "2023", "Coelho", "O começo de uma nova fase.", "Até o começo de 2023 ficou muita coisa dessa época guardada comigo."],
  ["🐉", "2024", "Dragão", "Você terminou comigo.", "Em 2024 você terminou comigo. Eu não lembro direito o motivo e não quero inventar uma coisa que talvez nem tenha sido assim. Só sei que depois disso muita coisa mudou."],
  ["🐍", "2025", "Serpente", "A vida foi seguindo.", "Muita coisa mudou, mas algumas lembranças continuam sendo importantes pra mim."],
  ["🐎", "2026", "Cavalo", "Onde eu estou agora.", "Hoje estou treinando e estudando pra ser policial militar, justamente algo que eu tinha falado lá no começo que queria ser."]
];
const grid=document.querySelector('#zodiacGrid'), box=document.querySelector('#messageBox');
years.forEach(s=>{const card=document.createElement('button');card.className='zodiac-card';card.innerHTML=`<div class="animal">${s[0]}</div><div class="animal-name">${s[1]} — ${s[2]}</div><div class="years">${s[3]}</div>`;card.onclick=()=>{document.querySelectorAll('.zodiac-card').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');box.classList.remove('show');setTimeout(()=>{box.innerHTML=`<div class="message-seal">福</div><div><div class="message-title">${s[1]} — ${s[2]}</div><p class="message-text">${s[4]}</p></div>`;box.classList.add('show');},120)};grid.appendChild(card)});
document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.querySelector(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
const petals=document.querySelector('#petals');function makePetal(){const p=document.createElement('span');p.className='petal';p.textContent=Math.random()>.35?'🌸':'✦';p.style.left=Math.random()*100+'vw';p.style.setProperty('--drift',(Math.random()*240-120)+'px');p.style.animationDuration=(7+Math.random()*8)+'s';p.style.fontSize=(10+Math.random()*14)+'px';petals.appendChild(p);setTimeout(()=>p.remove(),16000)}setInterval(makePetal,650);
const music=document.querySelector('#bgMusic'),musicBtn=document.querySelector('#musicBtn');

// Música padrão do site: Escrevi sobre você - Magyn (youtube).mp3
// O navegador pode bloquear autoplay com som; nesse caso, a primeira interação inicia a música.
function startBackgroundMusic(){
  if(!music || !music.paused)return;
  music.play().then(()=>musicBtn?.classList.add('active')).catch(()=>{});
}
musicBtn.onclick=async()=>{if(music.paused){try{await music.play();musicBtn.classList.add('active')}catch(e){}}else{music.pause();musicBtn.classList.remove('active')}};
music.onended=()=>musicBtn.classList.remove('active');
window.addEventListener('load',startBackgroundMusic);
document.addEventListener('pointerdown',startBackgroundMusic,{once:true});

// Jogo: dragão chinês desenhado no canvas, crescendo devagar ao pegar maçãs.
const canvas=document.querySelector('#dragonGame'),startBtn=document.querySelector('#startGame'),scoreEl=document.querySelector('#score'),highEl=document.querySelector('#highScore');
if(canvas){const ctx=canvas.getContext('2d');const COLS=28,ROWS=18;let dragon,dir,nextDir,apple,score,running=false,timer=null,high=Number(localStorage.getItem('dragonHighScore')||0);highEl.textContent=high;
function size(){return canvas.width/COLS}function resize(){canvas.width=Math.max(280,Math.min(canvas.parentElement.clientWidth-24,760));canvas.height=Math.round(canvas.width*ROWS/COLS);draw()}function reset(){dragon=[];let x=Math.floor(COLS/2),y=Math.floor(ROWS/2);for(let i=0;i<5;i++)dragon.push({x:x-i,y});dir={x:1,y:0};nextDir={x:1,y:0};score=0;scoreEl.textContent=0;newApple();draw()}function newApple(){do{apple={x:Math.floor(Math.random()*COLS),y:Math.floor(Math.random()*ROWS)}}while(dragon.some(s=>s.x===apple.x&&s.y===apple.y))}function rr(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function drawSeg(s,i){let z=size(),x=s.x*z,y=s.y*z,p=z*.1;ctx.fillStyle=i===0?'#b92735':'#d5a13a';rr(x+p,y+p,z-p*2,z-p*2,z*.28);ctx.fill();ctx.strokeStyle='#4b1717';ctx.lineWidth=Math.max(1,z*.055);ctx.stroke();ctx.fillStyle='#f3d46c';ctx.beginPath();ctx.arc(x+z*.3,y+z*.35,z*.09,0,Math.PI*2);ctx.arc(x+z*.7,y+z*.65,z*.09,0,Math.PI*2);ctx.fill();if(i===0){ctx.fillStyle='#d94b3d';ctx.beginPath();ctx.arc(x+z*.25,y+z*.17,z*.16,0,Math.PI*2);ctx.arc(x+z*.75,y+z*.17,z*.16,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff0b0';ctx.beginPath();ctx.arc(x+z*.34,y+z*.42,z*.1,0,Math.PI*2);ctx.arc(x+z*.66,y+z*.42,z*.1,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17110f';ctx.beginPath();ctx.arc(x+z*.34,y+z*.42,z*.045,0,Math.PI*2);ctx.arc(x+z*.66,y+z*.42,z*.045,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#f2c14e';ctx.beginPath();ctx.arc(x+z*.5,y+z*.58,z*.2,0,Math.PI);ctx.stroke()}}
function drawApple(){let z=size(),x=apple.x*z,y=apple.y*z;ctx.fillStyle='#c52b35';ctx.beginPath();ctx.arc(x+z*.4,y+z*.55,z*.22,0,Math.PI*2);ctx.arc(x+z*.6,y+z*.55,z*.22,0,Math.PI*2);ctx.fill();ctx.fillStyle='#4f8036';ctx.beginPath();ctx.ellipse(x+z*.65,y+z*.22,z*.15,z*.08,-.35,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#6b351f';ctx.beginPath();ctx.moveTo(x+z*.52,y+z*.3);ctx.lineTo(x+z*.5,y+z*.12);ctx.stroke()}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='rgba(28,18,18,.86)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='rgba(235,190,90,.08)';for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x*size(),0);ctx.lineTo(x*size(),canvas.height);ctx.stroke()}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y*size());ctx.lineTo(canvas.width,y*size());ctx.stroke()}drawApple();for(let i=dragon.length-1;i>=0;i--)drawSeg(dragon[i],i)}
function step(){if(!running)return;if(!(nextDir.x===-dir.x&&nextDir.y===-dir.y))dir=nextDir;let head={x:dragon[0].x+dir.x,y:dragon[0].y+dir.y};if(head.x<0||head.x>=COLS||head.y<0||head.y>=ROWS||dragon.some((s,i)=>i>0&&s.x===head.x&&s.y===head.y)){running=false;clearInterval(timer);startBtn.textContent='Jogar de novo';return}dragon.unshift(head);if(head.x===apple.x&&head.y===apple.y){score++;scoreEl.textContent=score;if(score>high){high=score;highEl.textContent=high;localStorage.setItem('dragonHighScore',high)}newApple();clearInterval(timer);timer=setInterval(step,Math.max(100,155-score*2))}else dragon.pop();draw()}
function start(){reset();running=true;startBtn.textContent='Reiniciar';clearInterval(timer);timer=setInterval(step,155)}function setDir(x,y){if(!(x===-dir.x&&y===-dir.y))nextDir={x,y}}document.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(k==='arrowup'||k==='w')setDir(0,-1);if(k==='arrowdown'||k==='s')setDir(0,1);if(k==='arrowleft'||k==='a')setDir(-1,0);if(k==='arrowright'||k==='d')setDir(1,0)});document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>{let d=b.dataset.dir;setDir(d==='up'?0:d==='down'?0:d==='left'?-1:1,d==='up'?-1:d==='down'?1:0)});startBtn.onclick=start;window.addEventListener('resize',resize);reset();resize()}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('reveal')}),{threshold:.12});document.querySelectorAll('.section,.timeline-card,.paper').forEach(el=>observer.observe(el));
